Fix(FavoriteRow): Correct toast action prop
The error `src/components/FavoriteRow.tsx(32,11): error TS2353: Object literal may only specify known properties, and 'altText' does not exist in type 'ReactElement<ForwardRefExoticComponent<Omit<ToastActionProps & RefAttributes<HTMLButtonElement>, "ref"> & RefAttributes<HTMLButtonElement>>, string | JSXElementConstructor<...>>'.` indicates an incorrect prop being passed to the `toast` action. This commit corrects the prop to the correct one.